class WINDOW:
	WIDTH = 1000
	HEIGHT = 1000
	TITLE = "Maze Explorer"
	SIZE = WIDTH, HEIGHT

class MAP:
	SEED = 100

	ROWS = 3
	COLS = 3
	SIZE = ROWS, COLS
	SPACING_TO_WIDTH_RATIO = 0.05

	ROOM_WIDTH = 5
	ROOM_HEIGHT = 5
	ROOM_SIZE = (ROOM_WIDTH, ROOM_HEIGHT)

	CELL_SPACING = (WINDOW.WIDTH / COLS) * SPACING_TO_WIDTH_RATIO
	CELL_WIDTH = WINDOW.WIDTH / COLS - CELL_SPACING
	CELL_HEIGHT = WINDOW.HEIGHT / ROWS - CELL_SPACING

class COLOURS:
	GREEN = (0, 255, 0)
	RED = (255, 0, 0)
	BLUE = (0, 0, 125)
	BLACK = (0, 0, 0)
	GREY = (55, 55, 55)
