import pygame


class WINDOW:
	WIDTH = 1000
	HEIGHT = 1000
	TITLE = "Maze Explorer"
	SIZE = WIDTH, HEIGHT
	FPS = 60

class CAMERA:
	ZOOM = 1
	WIDTH = WINDOW.WIDTH / ZOOM
	HEIGHT = WINDOW.HEIGHT / ZOOM

	SIZE = WIDTH, HEIGHT

class SPRITES:
	WIDTH = 32
	HEIGHT = 32
	SIZE = (WIDTH, HEIGHT)

class MAP:
	SPACING_TO_WIDTH_RATIO = 0.05

	# MAZE GENERATION
	SEED = 100
	ROWS = 5
	COLS = 5

	# RENDERING
	CELL_SPACING = (WINDOW.WIDTH / COLS) * SPACING_TO_WIDTH_RATIO
	CELL_WIDTH = WINDOW.WIDTH / COLS - CELL_SPACING
	CELL_HEIGHT = WINDOW.HEIGHT / ROWS - CELL_SPACING

	# MAZE -> WORLD GENERATION
	MAP_SIZE = ROWS, COLS

	ROOM_WIDTH = 9
	ROOM_HEIGHT = 9
	ROOM_SIZE = (ROOM_WIDTH, ROOM_HEIGHT)

	# ROOMS GENERATION -> ECS ARCHITECTURE
	GRID_ROWS = int(ROWS * ROOM_HEIGHT)
	GRID_COLS = int(COLS * ROOM_WIDTH)
	GRID_SIZE = GRID_ROWS, GRID_COLS

	# WORLD
	WORLD_WIDTH = GRID_ROWS * SPRITES.WIDTH
	WORLD_HEIGHT = GRID_ROWS * SPRITES.HEIGHT
	WORLD_SIZE = (WORLD_WIDTH, WORLD_HEIGHT)

class COLOURS:
	GREEN = (0, 255, 0)
	RED = (255, 0, 0)
	BLUE = (0, 0, 125)
	BLACK = (0, 0, 0)
	GREY = (55, 55, 55)

class CONTROLS:
	UP = (pygame.K_w, pygame.K_UP)
	DOWN = (pygame.K_s, pygame.K_DOWN)
	LEFT = (pygame.K_a, pygame.K_LEFT)
	RIGHT = (pygame.K_d, pygame.K_RIGHT)

class DEBUG:
	PLAYER_COLOR = COLOURS.GREY
	WALL_COLOR = COLOURS.GREEN
	DOOR_COLOR = COLOURS.BLUE