import pygame
import time

pygame.init()

class WINDOW:
	WIDTH = 1000
	HEIGHT = 1000
	CENTER = WIDTH // 2, HEIGHT // 2
	TITLE = "Maze Explorer"
	SIZE = WIDTH, HEIGHT

	DEFAULT_SIZE = SIZE
	DEFAULT_CENTER = CENTER
	
	FPS = 60
	CLOCK = pygame.Clock()

class UPDATE:
	INPUTS_CHECKS_PER_SEC = 10
	RAYCASTS_PER_SEC = 5

class CAMERA:
	ZOOM = 2
	WIDTH = WINDOW.WIDTH / ZOOM
	HEIGHT = WINDOW.HEIGHT / ZOOM

	SIZE = WIDTH, HEIGHT

class SPRITES:
	WIDTH = 16
	HEIGHT = 16
	SIZE = (WIDTH, HEIGHT)

class MAP:
	SPACING_TO_WIDTH_RATIO = 0.05

	# MAZE GENERATION
	SEED = time.time()
	ROWS = 6
	COLS = 6

	# RENDERING
	CELL_SPACING = (WINDOW.WIDTH / COLS) * SPACING_TO_WIDTH_RATIO
	CELL_WIDTH = WINDOW.WIDTH / COLS - CELL_SPACING
	CELL_HEIGHT = WINDOW.HEIGHT / ROWS - CELL_SPACING

	# MAZE -> WORLD GENERATION
	MAP_SIZE = ROWS, COLS

	ROOM_WIDTH = 9
	ROOM_HEIGHT = 9
	ROOM_SIZE = (ROOM_WIDTH, ROOM_HEIGHT)

	# ROOMS GENERATION -> ECS ARCHITECTURE
	GRID_ROWS = int(ROWS * (ROOM_HEIGHT - 1)) + 1
	GRID_COLS = int(COLS * (ROOM_WIDTH - 1)) + 1
	GRID_SIZE = GRID_COLS, GRID_ROWS

	# WORLD
	WORLD_WIDTH = GRID_ROWS * SPRITES.WIDTH
	WORLD_HEIGHT = GRID_ROWS * SPRITES.HEIGHT
	WORLD_SIZE = (WORLD_WIDTH, WORLD_HEIGHT)


class GAME:
	PLAYER_SPEED = 12
	PLAYER_LIGHT_STRENGTH = 128 # Out of 255 -> Alpha Strength
	PLAYER_LIGHT_RADIUS_AS_PERCENT_OF_SCREEN_AREA = 0.3
	NUMBER_OF_GUARDS = MAP.ROWS * MAP.COLS // 2
	GUARD_CHANGE_DIRECTION_TIME_DELAY = 4 # SECS
	RAYCAST_SHAPE_ACCURACY = 1.0 # > Values mean less accurate

class COLOURS:
	GREEN = (0, 255, 0)
	REALLY_DARK_GRAY = (16, 16, 16)
	RED = (255, 0, 0)
	BLUE = (0, 0, 125)
	BLACK = (0, 0, 0)
	GREEN_GREY = (50, 50, 55)
	CYAN = (0, 255, 255)

	TRANSPARENT_LIGHT_COLOR = (0, 0, 0, GAME.PLAYER_LIGHT_STRENGTH)
	ZERO_ALPHA = (0, 0, 0, 0)

	GREY_HALF_ALPHA = (128, 128, 128, 128)

class CONTROLS:
	UP = (pygame.K_w, pygame.K_UP)
	DOWN = (pygame.K_s, pygame.K_DOWN)
	LEFT = (pygame.K_a, pygame.K_LEFT)
	RIGHT = (pygame.K_d, pygame.K_RIGHT)
	INTERACT = (pygame.K_e, pygame.K_x, pygame.K_RCTRL)

class MAIN_MENU_GAME_MODES:
	TITLES = ("   Easy   ", "   Hard   ", "  Insane  ", "Impossible")
	VALUES = (6, 13, 20, 40)

class DEBUG:
	PLAYER_COLOR = COLOURS.RED
	WALL_COLOR = COLOURS.GREEN
	DOOR_COLOR = COLOURS.BLUE
	FLOOR_COLOR = COLOURS.GREEN_GREY
	ARTIFACT_COLOR = COLOURS.CYAN
	RAYCAST_COLOR = COLOURS.GREY_HALF_ALPHA

class UI:
	PANEL_COLOR = (22, 22, 27)
	BUTTON_COLOR = COLOURS.GREEN_GREY
	HOVERED_BUTTON_COLOR = COLOURS.REALLY_DARK_GRAY
	TEXT_COLOR = COLOURS.BLACK
	BUTTON_DISTANCE_FROM_WINDOW_CENTER_AS_PERCENTAGE = 0.5

	BTN_FONT_SIZE = 48
	TITLE_FONT_SIZE = 96
	GAME_FONT_SIZE = 24

	FONT_NAME = "COURIER NEW"
	TITLE_FONT = pygame.font.SysFont(FONT_NAME, TITLE_FONT_SIZE, bold=True)
	BTN_FONT = pygame.font.SysFont(FONT_NAME, BTN_FONT_SIZE, bold=True)
	GAME_FONT = pygame.font.SysFont(FONT_NAME, GAME_FONT_SIZE, bold=True)

	TEXT_PADDING_AS_PERCENTAGE_OF_SIZE = 0.1

	MARGIN = 0.02

def update_map_constants():
	MAP.CELL_SPACING = (WINDOW.WIDTH / MAP.COLS) * MAP.SPACING_TO_WIDTH_RATIO
	MAP.CELL_WIDTH = WINDOW.WIDTH / MAP.COLS - MAP.CELL_SPACING
	MAP.CELL_HEIGHT = WINDOW.HEIGHT / MAP.ROWS - MAP.CELL_SPACING

	# MAZE -> WORLD GENERATION
	MAP.MAP_SIZE = MAP.ROWS, MAP.COLS

	# ROOMS GENERATION -> ECS ARCHITECTURE
	MAP.GRID_ROWS = int(MAP.ROWS * (MAP.ROOM_HEIGHT - 1)) + 1
	MAP.GRID_COLS = int(MAP.COLS *(MAP.ROOM_WIDTH - 1)) + 1
	MAP.GRID_SIZE = MAP.GRID_ROWS, MAP.GRID_COLS

	# WORLD
	MAP.WORLD_WIDTH = MAP.GRID_ROWS * SPRITES.WIDTH
	MAP.WORLD_HEIGHT = MAP.GRID_ROWS * SPRITES.HEIGHT
	MAP.WORLD_SIZE = (MAP.WORLD_WIDTH, MAP.WORLD_HEIGHT)

	# GAME
	GAME.NUMBER_OF_GUARDS = MAP.ROWS * MAP.COLS // 2