import pygame

class WINDOW:
	WIDTH = 1000
	HEIGHT = 1000
	TITLE = "Maze Explorer"
	SIZE = WIDTH, HEIGHT
	
	FPS = 60

class UPDATE:
	INPUTS_CHECKS_PER_SEC = 10
	RAYCASTS_PER_SEC = 5

class CAMERA:
	ZOOM = 2
	WIDTH = WINDOW.WIDTH / ZOOM
	HEIGHT = WINDOW.HEIGHT / ZOOM

	SIZE = WIDTH, HEIGHT

class SPRITES:
	WIDTH = 16
	HEIGHT = 16
	SIZE = (WIDTH, HEIGHT)

class MAP:
	SPACING_TO_WIDTH_RATIO = 0.05

	# MAZE GENERATION
	SEED = 100
	ROWS = 6
	COLS = 6

	# RENDERING
	CELL_SPACING = (WINDOW.WIDTH / COLS) * SPACING_TO_WIDTH_RATIO
	CELL_WIDTH = WINDOW.WIDTH / COLS - CELL_SPACING
	CELL_HEIGHT = WINDOW.HEIGHT / ROWS - CELL_SPACING

	# MAZE -> WORLD GENERATION
	MAP_SIZE = ROWS, COLS

	ROOM_WIDTH = 9
	ROOM_HEIGHT = 9
	ROOM_SIZE = (ROOM_WIDTH, ROOM_HEIGHT)

	# ROOMS GENERATION -> ECS ARCHITECTURE
	GRID_ROWS = int(ROWS * ROOM_HEIGHT)
	GRID_COLS = int(COLS * ROOM_WIDTH)
	GRID_SIZE = GRID_ROWS, GRID_COLS

	# WORLD
	WORLD_WIDTH = GRID_ROWS * SPRITES.WIDTH
	WORLD_HEIGHT = GRID_ROWS * SPRITES.HEIGHT
	WORLD_SIZE = (WORLD_WIDTH, WORLD_HEIGHT)

class GAME:
	PLAYER_SPEED = 12
	PLAYER_LIGHT_STRENGTH = 128 # Out of 255 -> Alpha Strength
	PLAYER_LIGHT_RADIUS_AS_PERCENT_OF_SCREEN_AREA = 0.3
	NUMBER_OF_GUARDS = MAP.ROWS * 2
	GUARD_CHANGE_DIRECTION_TIME_DELAY = 4 # SECS
	RAYCAST_SHAPE_ACCURACY = 1.0 # > Values mean less accurate

class COLOURS:
	GREEN = (0, 255, 0)
	RED = (255, 0, 0)
	BLUE = (0, 0, 125)
	BLACK = (0, 0, 0)
	GREY = (55, 55, 55)
	CYAN = (0, 255, 255)

	ZERO_ALPHA = (0, 0, 0, GAME.PLAYER_LIGHT_STRENGTH)
	GREY_HALF_ALPHA = (128, 128, 128, 128)

class CONTROLS:
	UP = (pygame.K_w, pygame.K_UP)
	DOWN = (pygame.K_s, pygame.K_DOWN)
	LEFT = (pygame.K_a, pygame.K_LEFT)
	RIGHT = (pygame.K_d, pygame.K_RIGHT)
	INTERACT = (pygame.K_e, pygame.K_RCTRL)


class DEBUG:
	PLAYER_COLOR = COLOURS.RED
	WALL_COLOR = COLOURS.GREEN
	DOOR_COLOR = COLOURS.BLUE
	FLOOR_COLOR = COLOURS.GREY
	ARTIFACT_COLOR = COLOURS.CYAN
	RAYCAST_COLOR = COLOURS.GREY_HALF_ALPHA